/**:
  ros__parameters:
    sync_queue_size: 20
    precision_threshold_to_judge_overlapped: 0.4
    recall_threshold_to_judge_overlapped: 0.5
    remove_overlapped_unknown_objects: true
    base_link_frame_id: base_link
    priority_mode: 3  # PriorityMode::Confidence
    # ClassBased priority for each object class
    class_based_priority.CAR: false
    class_based_priority.TRUCK: false
    class_based_priority.BUS: false
    class_based_priority.TRAILER: false
    class_based_priority.MOTORCYCLE: true
    class_based_priority.BICYCLE: true
    class_based_priority.PEDESTRIAN: true
    class_based_priority.UNKNOWN: false
    message_timeout_sec: 1.0
    initialization_timeout_sec: 10.0
