#!/usr/bin/env python3
"""Generate gRPC/protobuf Python code from .proto files.

Usage:
    python src/autoware_carla_interface/splatsim/generate_proto.py

The generated files are written to the proto/ directory alongside this script.
Import paths are automatically fixed for the package layout.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

_THIS_DIR = Path(__file__).resolve().parent
PROTO_DIR = _THIS_DIR / "proto"
OUT_DIR = PROTO_DIR


def main() -> None:
    proto_files = sorted(PROTO_DIR.glob("*.proto"))
    if not proto_files:
        print("No .proto files found under", PROTO_DIR, file=sys.stderr)
        sys.exit(1)

    cmd = [
        sys.executable,
        "-m",
        "grpc_tools.protoc",
        f"-I{PROTO_DIR}",
        f"--python_out={OUT_DIR}",
        f"--grpc_python_out={OUT_DIR}",
        f"--pyi_out={OUT_DIR}",
        *[str(p) for p in proto_files],
    ]
    print("Running:", " ".join(cmd))
    subprocess.check_call(cmd)

    _flatten_and_fix_imports()
    print("Generated files in", OUT_DIR)


def _flatten_and_fix_imports() -> None:
    """Move files from nested subdirs to OUT_DIR and fix imports."""
    nested_files = [
        f
        for f in OUT_DIR.rglob("*.py*")
        if f.parent != OUT_DIR and f.suffix in (".py", ".pyi")
    ]

    for src in nested_files:
        dst = OUT_DIR / src.name
        dst.write_text(src.read_text())
        src.unlink()

    for d in sorted(OUT_DIR.rglob("*"), reverse=True):
        if d.is_dir() and d != OUT_DIR:
            try:
                d.rmdir()
            except OSError:
                pass

    for py_file in OUT_DIR.glob("*.py"):
        text = py_file.read_text()
        fixed = text
        # Fix nested package imports
        fixed = re.sub(
            r"from splatsim\.v1 import",
            "from autoware_carla_interface.splatsim.proto import",
            fixed,
        )
        # Fix bare imports (generated by grpc_tools for _grpc.py files)
        fixed = re.sub(
            r"^import rendering_service_pb2 as",
            "from autoware_carla_interface.splatsim.proto import rendering_service_pb2 as",
            fixed,
            flags=re.MULTILINE,
        )
        if fixed != text:
            py_file.write_text(fixed)
            print(f"  Fixed imports in {py_file.name}")


if __name__ == "__main__":
    main()
