# USE ONLY WHEN THE OPTION COMPILE_WITH_OLD_ARCHITECTURE IS SET TO FALSE.
# https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_path_planner/CMakeLists.txt
# NOTE: The smaller the priority number is, the higher the module priority is.
/**:
  ros__parameters:
    external_request_lane_change_left:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: false
      enable_simultaneous_execution_as_candidate_module: true
      keep_last: false
      priority: 6

    external_request_lane_change_right:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: false
      enable_simultaneous_execution_as_candidate_module: true
      keep_last: false
      priority: 6

    lane_change_left:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: true
      enable_simultaneous_execution_as_candidate_module: true
      keep_last: false
      priority: 5

    lane_change_right:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: true
      enable_simultaneous_execution_as_candidate_module: true
      keep_last: false
      priority: 5

    start_planner:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: false
      enable_simultaneous_execution_as_candidate_module: false
      keep_last: false
      priority: 0

    side_shift:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: false
      enable_simultaneous_execution_as_candidate_module: false
      keep_last: false
      priority: 2

    goal_planner:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: false
      enable_simultaneous_execution_as_candidate_module: false
      keep_last: true
      priority: 1

    static_obstacle_avoidance:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: true
      enable_simultaneous_execution_as_candidate_module: false
      keep_last: false
      priority: 4

    avoidance_by_lane_change:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: false
      enable_simultaneous_execution_as_candidate_module: false
      keep_last: false
      priority: 3

    dynamic_obstacle_avoidance:
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: true
      enable_simultaneous_execution_as_candidate_module: true
      keep_last: false
      priority: 7

    sampling_planner:
      enable_module: true
      enable_rtc: false
      enable_simultaneous_execution_as_approved_module: false
      enable_simultaneous_execution_as_candidate_module: false
      keep_last: true
      priority: 16
