<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>autoware_safety_planner</name>
  <version>0.0.1</version>
  <description>Safety Planner</description>
  <maintainer email="takumi.odashima@tier4.jp">Takumi Odashima</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>
  <buildtool_depend>generate_parameter_library</buildtool_depend>

  <depend>autoware_internal_debug_msgs</depend>
  <depend>autoware_internal_planning_msgs</depend>
  <depend>autoware_lanelet2_utils</depend>
  <depend>autoware_map_msgs</depend>
  <depend>autoware_osqp_interface</depend>
  <depend>autoware_perception_msgs</depend>
  <depend>autoware_planning_msgs</depend>
  <depend>autoware_trajectory</depend>
  <depend>autoware_trajectory_optimizer</depend>
  <depend>autoware_utils</depend>
  <depend>autoware_utils_debug</depend>
  <depend>autoware_utils_geometry</depend>
  <depend>autoware_utils_system</depend>
  <depend>autoware_utils_uuid</depend>
  <depend>autoware_utils_visualization</depend>
  <depend>autoware_vehicle_info_utils</depend>
  <depend>autoware_vehicle_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>sensor_msgs</depend>
  <depend>unique_identifier_msgs</depend>
  <depend>visualization_msgs</depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
