#!/usr/bin/env python3
"""Generate `ml_package_<model>.param.yaml` from exported artifacts.

The node reads every network-describing value (tensor names, voxelization
geometry, temporal contract, horizon) from a param file that ships WITH the
model, the way autoware_bevfusion does. This script derives that file from what
the exporter already produced, so a new checkpoint cannot silently disagree
with a hand-edited config:

- the planner ONNX supplies its input/output tensor names and the horizon;
- the extractor ONNX supplies points-per-voxel and point-feature count from the
  `voxels` input shape, and its sidecar JSON supplies the voxel grid;
- the deployment contract JSON supplies the temporal cache semantics.

Usage:
    make_ml_package_param.py MODEL_DIR [--model-name resworld]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import onnx


def _tensor_shape(model: onnx.ModelProto, name: str) -> list:
    for value in list(model.graph.input) + list(model.graph.output):
        if value.name == name:
            return [d.dim_value if d.dim_value else (d.dim_param or -1)
                    for d in value.type.tensor_type.shape.dim]
    raise KeyError(f"{name} is not an input or output of the graph")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("model_dir", type=Path)
    parser.add_argument("--model-name", default="resworld")
    parser.add_argument("--planner-onnx", default=None)
    parser.add_argument("--extractor-onnx", default=None)
    parser.add_argument("--contract", default=None)
    parser.add_argument(
        "--planner-precision", default="fp32",
        help="TensorRT precision this graph is validated in (fp32 is the safe default: "
             "graphs with embedded normalization statistics overflow fp16 and TensorRT "
             "clips them silently)")
    parser.add_argument("--extractor-precision", default="fp16")
    parser.add_argument(
        "--turn-indicators-optional", action="store_true",
        help="the network declares turn_indicators but never reads it (verify by "
        "perturbing the input); let the node run without the report",
    )
    args = parser.parse_args()

    model_dir: Path = args.model_dir.expanduser().resolve()
    planner_path = model_dir / (args.planner_onnx or f"{args.model_name}_planner.simplified.onnx")
    extractor_path = model_dir / (args.extractor_onnx or "bevfusion_lidar_feature.onnx")
    contract_path = model_dir / (args.contract or f"{args.model_name}_deployment_contract.json")
    for path in (planner_path, extractor_path, contract_path):
        if not path.is_file():
            raise SystemExit(f"missing artifact: {path}")

    contract = json.loads(contract_path.read_text())
    cache = contract["temporal_cache"]
    alignment = cache.get("alignment", {})

    planner = onnx.load(str(planner_path), load_external_data=False)
    planner_inputs = [i.name for i in planner.graph.input]
    planner_outputs = [o.name for o in planner.graph.output]
    # [B, T, 4] or [B, A, T, 4]: the horizon is the second-to-last axis.
    trajectory_shape = _tensor_shape(planner, planner_outputs[0])
    horizon_steps = int(trajectory_shape[-2])

    extractor = onnx.load(str(extractor_path), load_external_data=False)
    voxels_shape = _tensor_shape(extractor, "voxels")
    max_points_per_voxel = int(voxels_shape[1])
    point_features = int(voxels_shape[2])
    feature_tensor = [o.name for o in extractor.graph.output][0]

    extractor_meta_path = extractor_path.with_suffix(".json")
    meta = json.loads(extractor_meta_path.read_text()) if extractor_meta_path.is_file() else {}
    voxelization = meta.get("voxelization", {})
    point_cloud_range = voxelization.get("point_cloud_range", [-122.4, -122.4, -3.0, 122.4, 122.4, 5.0])
    voxel_size = voxelization.get("voxel_size", [0.17, 0.17, 0.2])
    voxels_num = voxelization.get("voxels_num", [1, 128000, 256000])

    history_tensor = next(
        (name for name in planner_inputs if "bev_feature" in name), "bev_feature_history")
    prediction_tensor = planner_outputs[0]
    extras = [name for name in planner_outputs[1:]]
    time_step = float(cache.get("trajectory_interval_seconds", 0.1))

    lines = [
        "# GENERATED by autoware_tensorrt_e2e/scripts/make_ml_package_param.py — do not",
        "# hand-edit: regenerate it whenever the artifacts in this directory change.",
        f"# planner:   {planner_path.name}",
        f"# extractor: {extractor_path.name}",
        f"# contract:  {contract_path.name}",
        "#",
        "# This file describes the NETWORK and overrides the package defaults for it.",
        "# Host and deployment behaviour (workspace, rates, tolerances, paths)",
        "# stays in the package's model-agnostic e2e_planner.param.yaml.",
        "/**:",
        "  ros__parameters:",
        "    # Which input providers this model needs, matched by tensor name.",
        '    sensor_inputs: ["bev_feature"]',
        "    enable_context_inputs: true",
        "",
        "    # Precision this graph is validated in; overrides the package default.",
        f"    precision: \"{args.planner_precision}\"",
        "",
        *(
            [
                "    context:",
                "      # The graph carries this input for a stable signature only;",
                "      # perturbing it changes no output. Do not stall on it.",
                "      turn_indicators_required: false",
                "",
            ]
            if args.turn_indicators_optional
            else []
        ),
        "    bev_feature:",
        f"      history_tensor: \"{history_tensor}\"",
        f"      frames: {int(cache['frames'])}",
        f"      interval_seconds: {float(cache['interval_seconds'])}",
        f"      bev_half_extent_m: {float(alignment.get('bev_half_extent_m', 122.4))}",
        "      extractor:",
        f"        precision: \"{args.extractor_precision}\"",
        f"        feature_tensor: \"{feature_tensor}\"",
        f"        max_points_per_voxel: {max_points_per_voxel}  # from the voxels input shape",
        f"        use_intensity: {'true' if point_features >= 5 else 'false'}"
        f"  # {point_features} point features",
        f"        voxels_num: {voxels_num}  # [min, opt, max]",
        f"        point_cloud_range: {point_cloud_range}",
        f"        voxel_size: {voxel_size}",
        "",
        "    postprocess:",
        f"      prediction_tensor: \"{prediction_tensor}\"",
        f"      extra_trajectory_tensors: {json.dumps(extras)}",
        f"      horizon_seconds: {round(horizon_steps * time_step, 3)}"
        f"  # {horizon_steps} steps",
        f"      time_step: {time_step}",
        f"      generator_name: \"TensorrtE2e{args.model_name.capitalize()}\"",
        "",
    ]
    out_path = model_dir / f"ml_package_{args.model_name}.param.yaml"
    out_path.write_text("\n".join(lines))
    print(f"wrote {out_path}")
    print(f"  frames={cache['frames']} interval={cache['interval_seconds']}s "
          f"points/voxel={max_points_per_voxel} features={point_features} "
          f"horizon={horizon_steps} steps")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
