/**:
  ros__parameters:
    intensity_threshold: 1.0
    existence_probability_threshold: 0.2
    max_x: 60.0
    min_x: -20.0
    max_y: 20.0
    min_y: -20.0
    filter_target_label:
      UNKNOWN: true
      CAR: false
      TRUCK: false
      BUS: false
      TRAILER: false
      MOTORCYCLE: false
      BICYCLE: false
      PEDESTRIAN: false
