// Copyright 2026 TIER IV, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "autoware/tensorrt_e2e/bev_feature/bev_warp.hpp"

#include <gtest/gtest.h>
#include <nlohmann/json.hpp>

#include <cuda_runtime_api.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <string>
#include <vector>

namespace autoware::tensorrt_e2e
{

namespace
{

// Golden data generated by the ResWorld deployment reference implementation
// (`deployment/temporal.py::warp_bev_feature_to_current`) via OnePlanner's
// `projects/resworld/scripts/gen_bev_warp_goldens.py`. The reference composes the
// relative SE(2) transform in float64, so these goldens carry the numerically
// trustworthy answer for UTM-scale poses.
std::string data_dir()
{
  return std::string(TENSORRT_E2E_TEST_DATA_DIR) + "/bev_warp";
}

std::vector<float> read_floats(const std::string & path, const size_t expected)
{
  std::ifstream file(path, std::ios::binary);
  if (!file) {
    ADD_FAILURE() << "cannot open " << path;
    return {};
  }
  std::vector<float> values(expected);
  file.read(reinterpret_cast<char *>(values.data()), expected * sizeof(float));
  EXPECT_EQ(static_cast<size_t>(file.gcount()), expected * sizeof(float)) << path;
  return values;
}

bool cuda_available()
{
  int count = 0;
  return cudaGetDeviceCount(&count) == cudaSuccess && count > 0;
}

}  // namespace

TEST(BevWarpGoldenTest, MatchesDeploymentReferenceOnGpu)
{
  if (!cuda_available()) {
    GTEST_SKIP() << "no CUDA device";
  }

  nlohmann::json manifest;
  {
    std::ifstream file(data_dir() + "/cases.json");
    ASSERT_TRUE(file) << "missing " << data_dir() << "/cases.json";
    file >> manifest;
  }
  const auto channels = manifest.at("channels").get<int32_t>();
  const auto height = manifest.at("height").get<int32_t>();
  const auto width = manifest.at("width").get<int32_t>();
  const size_t elements = static_cast<size_t>(channels) * height * width;

  const auto feature =
    read_floats(data_dir() + "/" + manifest.at("feature").get<std::string>(), elements);
  ASSERT_EQ(feature.size(), elements);

  float * d_source = nullptr;
  float * d_output = nullptr;
  ASSERT_EQ(cudaMalloc(&d_source, elements * sizeof(float)), cudaSuccess);
  ASSERT_EQ(cudaMalloc(&d_output, elements * sizeof(float)), cudaSuccess);
  ASSERT_EQ(
    cudaMemcpy(d_source, feature.data(), elements * sizeof(float), cudaMemcpyHostToDevice),
    cudaSuccess);

  // Full-range standard-normal features; the gate is expressed against that unit scale.
  // Measured headroom: worst case 9e-6 (float rounding in the bilinear weights) once the
  // relative transform is composed in double — per-cell world-frame float32 arithmetic at UTM
  // pose magnitude fails this gate by ~30x.
  constexpr float kTolerance = 1.0e-4f;

  for (const auto & test_case : manifest.at("cases")) {
    const auto name = test_case.at("name").get<std::string>();
    const auto golden =
      read_floats(data_dir() + "/" + test_case.at("golden").get<std::string>(), elements);
    ASSERT_EQ(golden.size(), elements) << name;

    std::array<double, 4> current_pose{};
    std::array<double, 4> source_pose{};
    for (int i = 0; i < 4; ++i) {
      current_pose[i] = test_case.at("current_pose")[i].get<double>();
      source_pose[i] = test_case.at("source_pose")[i].get<double>();
    }
    const Se2WarpParams params = make_se2_warp_params(
      current_pose, source_pose, manifest.at("half_extent_m").get<double>(), height, width);

    ASSERT_EQ(launch_se2_warp_kernel(d_source, d_output, params, channels, nullptr), cudaSuccess)
      << name;
    std::vector<float> output(elements);
    ASSERT_EQ(
      cudaMemcpy(output.data(), d_output, elements * sizeof(float), cudaMemcpyDeviceToHost),
      cudaSuccess)
      << name;

    float max_error = 0.0f;
    for (size_t i = 0; i < elements; ++i) {
      max_error = std::max(max_error, std::abs(output[i] - golden[i]));
    }
    RecordProperty(name + "_max_error", std::to_string(max_error));
    EXPECT_LE(max_error, kTolerance) << name << ": max|err|=" << max_error;
  }

  cudaFree(d_source);
  cudaFree(d_output);
}

}  // namespace autoware::tensorrt_e2e
