/**:
  ros__parameters:
    planning_frequency_hz: 10.0

    ego_nearest_lanelet:
      dist_threshold_m: 6.0 # [m]
      yaw_threshold_rad: 1.57 # [rad]

    reference_path:
      policy: "goal_connection_and_smooth" # simple / goal_connection / goal_connection_and_smooth
      goal_connection:
        search_radius_m: 15.0 # [m]
      smoother:
        clearance_m: 1.0 # [m]
      forward_length_m: 200.0 # [m]
      backward_length_m: 15.0 # [m]

    engage_velocity:
      enable: true
      velocity_hard_mps: 0.3 # [m/s]

    constraint_generator_plugins:
      - "autoware::safety_planner::experiment::VehicleKinematicsConstraintGenerator"
      - "autoware::safety_planner::experiment::LaneFollowingDrivableAreaConstraintGenerator"
      - "autoware::safety_planner::experiment::ObstacleStopConstraintGenerator"

    trajectory_planner_plugin: "autoware::safety_planner::experiment::FrenetSamplingBasedPlanner"
