/**:
  ros__parameters:
    # plugins
    plugins_path: $(find-pkg-share autoware_tensorrt_plugins)/plugins/libautoware_tensorrt_plugins.so
    # network
    trt_precision: fp16
    cloud_capacity: 2000000
    onnx_path: "$(var model_path)/ptv3.onnx"
    engine_path: "$(var model_path)/ptv3.engine"
    colors_red:
      [
        0,
        0,
        233,
        110,
        0,
        232,
        255,
        0,
        255,
        255,
        160,
        255,
        255,
        220,
        255,
        230,
        128,
        255,
        47,
        139,
        218,
        128,
        135,
        0,
        170,
        205,
      ]
    colors_green:
      [
        0,
        255,
        233,
        110,
        175,
        35,
        158,
        0,
        0,
        127,
        60,
        140,
        215,
        20,
        61,
        230,
        128,
        0,
        79,
        69,
        165,
        0,
        206,
        0,
        170,
        133,
      ]
    colors_blue:
      [
        0,
        255,
        229,
        110,
        0,
        244,
        0,
        230,
        0,
        80,
        60,
        0,
        0,
        60,
        99,
        0,
        128,
        255,
        79,
        19,
        32,
        128,
        235,
        128,
        170,
        63,
      ]
    ground_prob_threshold: 0.05
