/**:
  ros__parameters:
    # Enable/disable filtering for objects
    enable_object_filtering: true

    # Enable/disable filtering for pointcloud
    enable_pointcloud_filtering: true

    # Distance from predicted path to filter objects [m]
    filter_distance: 3.0

    # Minimum distance from predicted path for pointcloud filtering [m]
    # Points closer than this distance are always kept
    min_distance: 1.0
