/**:
  ros__parameters:
    external_delay_tolerance: 5.0
    external_time_tolerance: 5.0
    perception_time_tolerance: 1.0
    external_priority: false
    enable_signal_matching: false
    prioritize_internal_signals_when_arrows_present: false # only matters when enable_signal_matching is true
