# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from autoware_carla_interface.splatsim.proto import rendering_service_pb2 as rendering__service__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rendering_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RenderingServiceStub(object):
    """── Service definition ───────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initialize = channel.unary_unary(
                '/splatsim.v1.RenderingService/Initialize',
                request_serializer=rendering__service__pb2.InitializeRequest.SerializeToString,
                response_deserializer=rendering__service__pb2.InitializeResponse.FromString,
                _registered_method=True)
        self.StreamCameraData = channel.stream_unary(
                '/splatsim.v1.RenderingService/StreamCameraData',
                request_serializer=rendering__service__pb2.CameraData.SerializeToString,
                response_deserializer=rendering__service__pb2.StreamSummary.FromString,
                _registered_method=True)


class RenderingServiceServicer(object):
    """── Service definition ───────────────────────────────────────────────

    """

    def Initialize(self, request, context):
        """Load scene, create renderer and publishers. Blocks until ready.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCameraData(self, request_iterator, context):
        """Client streams timestamped camera poses. Server renders at frame_rate
        cadence and publishes via DDS. Returns summary when stream closes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RenderingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=rendering__service__pb2.InitializeRequest.FromString,
                    response_serializer=rendering__service__pb2.InitializeResponse.SerializeToString,
            ),
            'StreamCameraData': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamCameraData,
                    request_deserializer=rendering__service__pb2.CameraData.FromString,
                    response_serializer=rendering__service__pb2.StreamSummary.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'splatsim.v1.RenderingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('splatsim.v1.RenderingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RenderingService(object):
    """── Service definition ───────────────────────────────────────────────

    """

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/splatsim.v1.RenderingService/Initialize',
            rendering__service__pb2.InitializeRequest.SerializeToString,
            rendering__service__pb2.InitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCameraData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/splatsim.v1.RenderingService/StreamCameraData',
            rendering__service__pb2.CameraData.SerializeToString,
            rendering__service__pb2.StreamSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
