/**:
  ros__parameters:
    # Filtering parameters
    enable_object_filtering: true
    enable_pointcloud_filtering: true
    max_filter_distance: 5.0  # [m]
    pointcloud_safety_distance: 1.0  # [m]
    object_classification_radius: 50.0  # [m]

    # RTC recreation on vehicle stop
    stop_velocity_threshold: 0.001  # [m/s] Velocity threshold to consider vehicle as stopped

    # Object classes to ignore during filtering
    # Available classes: UNKNOWN, CAR, TRUCK, BUS, TRAILER, MOTORCYCLE, BICYCLE, PEDESTRIAN
    # Example: ignore_object_classes: ["PEDESTRIAN", "BICYCLE"]  # Ignore pedestrians and bicycles
    ignore_object_classes: []  # Empty list means no objects are ignored

    # Debug parameters
    debug_timer_period: 0.1  # [s] Debug timer period (10Hz default)
