/**:
  ros__parameters:
    availability_dest_ip: "127.0.0.1"
    availability_dest_port: "59000"
    mrm_state_dest_ip: "127.0.0.1"
    mrm_state_dest_port: "59001"
    mrm_request_src_ip: "127.0.0.1"
    mrm_request_src_port: "59002"
    election_communication_src_ip: "127.0.0.1"
    election_communication_src_port: "59003"
    election_status_src_ip: "127.0.0.1"
    election_status_src_port: "59004"
    reset_request_dest_ip: "127.0.0.1"
    reset_request_dest_port: "59005"
    reset_response_src_ip: "127.0.0.1"
    reset_response_src_port: "59006"
