// Copyright 2026 TIER IV, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.

#ifndef AUTOWARE__PROXIMITY_HAZARD_OBJECT_CHECKER__PROXIMITY_HAZARD_OBJECT_CHECKER_HPP_
#define AUTOWARE__PROXIMITY_HAZARD_OBJECT_CHECKER__PROXIMITY_HAZARD_OBJECT_CHECKER_HPP_

// Auto-generated by generate_parameter_library. Verify the include path matches
// your CMake target name for the generated parameters library.
#include <autoware_proximity_hazard_object_checker/autoware_proximity_hazard_object_checker_param.hpp>
#include <autoware_proximity_hazard_object_checker/msg/proximity_hazard_objects.hpp>
#include <autoware_utils_geometry/boost_geometry.hpp>

#include <autoware_perception_msgs/msg/predicted_objects.hpp>
#include <autoware_perception_msgs/msg/shape.hpp>
#include <geometry_msgs/msg/transform_stamped.hpp>

#include <cstdint>
#include <optional>

namespace autoware::proximity_hazard_object_checker
{

// Pure logic: no Node, no subscriptions, no clock. Constructed from params and a
// pre-built vehicle footprint, then driven by `process()`. Easily unit-testable.
using autoware_perception_msgs::msg::PredictedObjects;
using autoware_proximity_hazard_object_checker::msg::ProximityHazardObjects;
using autoware_utils_geometry::LinearRing2d;
using autoware_utils_geometry::Polygon2d;

class ProximityHazardObjectChecker
{
public:
  ProximityHazardObjectChecker(
    proximity_hazard_object::Params params, LinearRing2d vehicle_footprint);

  // Build the per-sector hazard message from a PredictedObjects input and the
  // transform from the input's frame to base_link.
  ProximityHazardObjects process(
    const PredictedObjects & input,
    const geometry_msgs::msg::TransformStamped & to_base_link) const;

  // Maps a bearing in radians (any range; normalized internally) to a sector index
  // per the configured per-sector ranges. Returns nullopt if the bearing does not
  // fall in any configured sector (misconfiguration: gap or under-specified).
  std::optional<uint8_t> bearing_to_sector(double bearing_rad) const;

  // Bounding-circle pre-filter helper. Returns the radius of the smallest circle
  // centered at the object-local origin that contains the shape.
  static double compute_circumradius(const autoware_perception_msgs::msg::Shape & shape);

private:
  proximity_hazard_object::Params params_;
  LinearRing2d vehicle_footprint_;
  double vehicle_circumradius_;  // Max distance from base_link origin to any footprint vertex.
  double max_detection_range_squared_;  // Cached: params_.max_detection_range_m^2.
};

}  // namespace autoware::proximity_hazard_object_checker

#endif  // AUTOWARE__PROXIMITY_HAZARD_OBJECT_CHECKER__PROXIMITY_HAZARD_OBJECT_CHECKER_HPP_
