// Copyright 2026 The Autoware Foundation.
//
// Licensed under the Apache License, Version 2.0 (the "License");

#ifndef AUTOWARE__DATA_DRIVEN_PLANNING_SIMULATOR__VISIBILITY_CONTROL_HPP_
#define AUTOWARE__DATA_DRIVEN_PLANNING_SIMULATOR__VISIBILITY_CONTROL_HPP_

#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define DATA_DRIVEN_PLANNING_SIMULATOR_EXPORT __attribute__((dllexport))
    #define DATA_DRIVEN_PLANNING_SIMULATOR_IMPORT __attribute__((dllimport))
  #else
    #define DATA_DRIVEN_PLANNING_SIMULATOR_EXPORT __declspec(dllexport)
    #define DATA_DRIVEN_PLANNING_SIMULATOR_IMPORT __declspec(dllimport)
  #endif
  #ifdef DATA_DRIVEN_PLANNING_SIMULATOR_BUILDING_DLL
    #define DATA_DRIVEN_PLANNING_SIMULATOR_PUBLIC DATA_DRIVEN_PLANNING_SIMULATOR_EXPORT
  #else
    #define DATA_DRIVEN_PLANNING_SIMULATOR_PUBLIC DATA_DRIVEN_PLANNING_SIMULATOR_IMPORT
  #endif
  #define DATA_DRIVEN_PLANNING_SIMULATOR_PUBLIC_TYPE DATA_DRIVEN_PLANNING_SIMULATOR_PUBLIC
  #define DATA_DRIVEN_PLANNING_SIMULATOR_LOCAL
#else
  #define DATA_DRIVEN_PLANNING_SIMULATOR_EXPORT __attribute__((visibility("default")))
  #define DATA_DRIVEN_PLANNING_SIMULATOR_IMPORT
  #if __GNUC__ >= 4
    #define DATA_DRIVEN_PLANNING_SIMULATOR_PUBLIC __attribute__((visibility("default")))
    #define DATA_DRIVEN_PLANNING_SIMULATOR_LOCAL __attribute__((visibility("hidden")))
  #else
    #define DATA_DRIVEN_PLANNING_SIMULATOR_PUBLIC
    #define DATA_DRIVEN_PLANNING_SIMULATOR_LOCAL
  #endif
  #define DATA_DRIVEN_PLANNING_SIMULATOR_PUBLIC_TYPE
#endif

#endif  // AUTOWARE__DATA_DRIVEN_PLANNING_SIMULATOR__VISIBILITY_CONTROL_HPP_
