#!/usr/bin/env python3

# Copyright 2026 TIER IV, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Build test_data/scenarios/<name>.yaml for test/closed_loop with a GUI.

Map drawing and the lanelet id tooltip are reused as-is from test_case_generator.py of
autoware_lanelet2_utils. Start and goal are placed by dragging, and Generate writes the shortest path
found by the lanelet2 RoutingGraph as the segments of the yaml.
"""

from argparse import ArgumentParser
import importlib.util
import math
from pathlib import Path
import sys

from ament_index_python.packages import get_package_prefix
from ament_index_python.packages import get_package_share_directory
import lanelet2
import matplotlib.pyplot as plt
from matplotlib.widgets import Button
from matplotlib.widgets import TextBox

DEFAULT_MAP_URI = "package://autoware_test_utils/test_map/lanelet2_map.osm"
DEFAULT_VEHICLE_INFO_URI = "package://autoware_test_utils/config/test_vehicle_info.param.yaml"

# tolerances used when picking the lanelet under the start / goal pose
NEAREST_CANDIDATES = 16
MAX_YAW_DIFF = math.pi / 4.0


def import_lanelet2_utils_generator():
    # loaded from the install directory as a module, so that drawing and hover are not duplicated here
    path = (
        Path(get_package_prefix("autoware_lanelet2_utils"))
        / "lib/autoware_lanelet2_utils/test_case_generator.py"
    )
    spec = importlib.util.spec_from_file_location("lanelet2_utils_test_case_generator", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def resolve_pkg_share_uri(uri: str) -> Path:
    if not uri.startswith("package://"):
        return Path(uri)
    pkg, _, rel = uri[len("package://") :].partition("/")
    return Path(get_package_share_directory(pkg)) / rel


def lanelet_yaw_at(lanelet, x, y):
    centerline = lanelet.centerline
    nearest = min(
        range(len(centerline) - 1),
        key=lambda i: math.hypot(centerline[i].x - x, centerline[i].y - y),
    )
    return math.atan2(
        centerline[nearest + 1].y - centerline[nearest].y,
        centerline[nearest + 1].x - centerline[nearest].x,
    )


def find_lanelet(lanelet_map, traffic_rules, x, y, yaw):
    """Return the closest routable lanelet whose direction matches the pose (None if there is none).

    Lanelets the traffic rules do not allow (e.g. road_shoulder) are not in the RoutingGraph, so they
    are skipped here; a pose on a shoulder resolves to the adjacent road lanelet. The pose itself is
    kept as is, which is how mission_planner builds a route that starts or ends on a shoulder.
    """
    candidates = lanelet2.geometry.findNearest(
        lanelet_map.laneletLayer, lanelet2.core.BasicPoint2d(x, y), NEAREST_CANDIDATES
    )
    for _, lanelet in candidates:
        if not traffic_rules.canPass(lanelet):
            continue
        diff = abs(math.remainder(lanelet_yaw_at(lanelet, x, y) - yaw, 2.0 * math.pi))
        if diff < MAX_YAW_DIFF:
            return lanelet
    return None


def route_yaml(map_uri, vehicle_info_uri, start, goal, lanelet_ids) -> str:
    def pose_yaml(pose, indent):
        x, y, yaw = pose
        pad = " " * indent
        return (
            f"{pad}position:\n"
            f"{pad}  x: {x}\n"
            f"{pad}  y: {y}\n"
            f"{pad}  z: 0.0\n"
            f"{pad}orientation:\n"
            f"{pad}  x: 0.0\n"
            f"{pad}  y: 0.0\n"
            f"{pad}  z: {math.sin(yaw / 2.0)}\n"
            f"{pad}  w: {math.cos(yaw / 2.0)}\n"
        )

    # neighboring lanes are not added to primitives because the closed-loop test does not evaluate
    # lane changes
    segments = "".join(
        f"    - preferred_primitive:\n"
        f"        id: {lanelet_id}\n"
        f'        primitive_type: ""\n'
        f"      primitives:\n"
        f"        - id: {lanelet_id}\n"
        f"          primitive_type: lane\n"
        for lanelet_id in lanelet_ids
    )
    return (
        "# Generated by scripts/generate_test_data.py\n"
        "format_version: 1\n"
        f"map_path_uri: {map_uri}\n"
        f"vehicle_info_param_uri: {vehicle_info_uri}\n"
        "route:\n"
        "  start_pose:\n"
        f"{pose_yaml(start, 4)}"
        "  goal_pose:\n"
        f"{pose_yaml(goal, 4)}"
        "  segments:\n"
        f"{segments}"
    )


class PosePlacer:
    """Place start / goal by dragging (press point = position, direction to release point = yaw)."""

    def __init__(self, fig, ax, start_button_ax, goal_button_ax):
        self.fig, self.ax = fig, ax
        self.mode = None
        self.poses = {"start": None, "goal": None}
        self.artists = {"start": [], "goal": []}
        self.colors = {"start": "green", "goal": "red"}
        self.drag_from = None
        self.drag_artist = None

        self.buttons = {
            "start": Button(start_button_ax, "Set start"),
            "goal": Button(goal_button_ax, "Set goal"),
        }
        for key, button in self.buttons.items():
            button.on_clicked(lambda event, key=key: self.toggle_mode(key))
        self.refresh_buttons()

        fig.canvas.mpl_connect("button_press_event", self.on_press)
        fig.canvas.mpl_connect("motion_notify_event", self.on_motion)
        fig.canvas.mpl_connect("button_release_event", self.on_release)

    def refresh_buttons(self):
        for key, button in self.buttons.items():
            active = self.mode == key
            button.label.set_text(f"Drag {key}" if active else f"Set {key}")
            button.color = button.hovercolor = self.colors[key] if active else "gray"
        self.fig.canvas.draw_idle()

    def toggle_mode(self, key):
        self.mode = None if self.mode == key else key
        self.refresh_buttons()

    def on_press(self, event):
        if self.mode and event.inaxes == self.ax:
            self.drag_from = (event.xdata, event.ydata)

    def on_motion(self, event):
        if not self.drag_from or event.inaxes != self.ax:
            return
        if self.drag_artist:
            self.drag_artist.remove()
        x0, y0 = self.drag_from
        self.drag_artist = self.ax.arrow(
            x0, y0, event.xdata - x0, event.ydata - y0, head_width=0.5, head_length=0.8, fc="k"
        )
        self.fig.canvas.draw_idle()

    def on_release(self, event):
        if not self.drag_from or event.inaxes != self.ax:
            return
        if self.drag_artist:
            self.drag_artist.remove()
            self.drag_artist = None
        x0, y0 = self.drag_from
        self.drag_from = None
        yaw = math.atan2(event.ydata - y0, event.xdata - x0)
        key = self.mode
        self.poses[key] = (x0, y0, yaw)
        self.draw_pose(key)
        # disarm after one placement; placing the same pose repeatedly is not a normal workflow
        self.mode = None
        self.refresh_buttons()

    def draw_pose(self, key):
        for artist in self.artists[key]:
            artist.remove()
        x, y, yaw = self.poses[key]
        color = self.colors[key]
        self.artists[key] = [
            self.ax.arrow(
                x,
                y,
                3.0 * math.cos(yaw),
                3.0 * math.sin(yaw),
                head_width=1.0,
                head_length=1.0,
                fc=color,
                ec=color,
            ),
            self.ax.text(x, y, key, color=color, fontsize=10),
        ]
        self.fig.canvas.draw_idle()


def main():
    parser = ArgumentParser()
    parser.add_argument("--map-uri", default=DEFAULT_MAP_URI)
    parser.add_argument("--vehicle-info-uri", default=DEFAULT_VEHICLE_INFO_URI)
    parser.add_argument(
        "--out-dir",
        # with a symlink install __file__ points at the source, so this writes to the source test_data
        default=str(Path(__file__).resolve().parent.parent / "test_data" / "scenarios"),
        help="directory the scenario yaml is written to",
    )
    args = parser.parse_args()

    if not Path(args.out_dir).is_dir():
        sys.exit(f"output directory not found: {args.out_dir} (pass --out-dir)")

    map_path = resolve_pkg_share_uri(args.map_uri)
    if not map_path.exists():
        sys.exit(f"map not found: {map_path}")

    lanelet2_utils = import_lanelet2_utils_generator()
    projector = lanelet2_utils.MGRSProjector()
    lanelet_map = lanelet2_utils.load_properly_projected_map(str(map_path), projector)
    traffic_rules = lanelet2.traffic_rules.create(
        lanelet2.traffic_rules.Locations.Germany, lanelet2.traffic_rules.Participants.Vehicle
    )
    routing_graph = lanelet2.routing.RoutingGraph(lanelet_map, traffic_rules)

    fig, ax = plt.subplots(figsize=(14, 9))
    lanelet2_utils.LaneletVisualizationHandler(fig, ax, str(map_path))
    fig.subplots_adjust(left=0.05, right=0.8, top=0.95, bottom=0.05)

    placer = PosePlacer(
        fig, ax, plt.axes([0.82, 0.80, 0.15, 0.06]), plt.axes([0.82, 0.72, 0.15, 0.06])
    )
    name_box = TextBox(plt.axes([0.82, 0.62, 0.15, 0.06]), "", initial="new_route")
    status = fig.text(0.82, 0.40, "", fontsize=9, wrap=True, va="top")

    def on_generate(event):
        start, goal = placer.poses["start"], placer.poses["goal"]
        if not start or not goal:
            status.set_text("place start and goal first")
            fig.canvas.draw_idle()
            return
        start_lanelet = find_lanelet(lanelet_map, traffic_rules, *start)
        goal_lanelet = find_lanelet(lanelet_map, traffic_rules, *goal)
        if not start_lanelet or not goal_lanelet:
            which = "start" if not start_lanelet else "goal"
            status.set_text(f"no lanelet matches the {which} heading")
            fig.canvas.draw_idle()
            return
        route = routing_graph.getRoute(start_lanelet, goal_lanelet)
        if not route:
            status.set_text(f"no route from {start_lanelet.id} to {goal_lanelet.id}")
            fig.canvas.draw_idle()
            return
        lanelet_ids = [lanelet.id for lanelet in route.shortestPath()]
        out_path = Path(args.out_dir) / f"{name_box.text}.yaml"
        out_path.write_text(
            route_yaml(args.map_uri, args.vehicle_info_uri, start, goal, lanelet_ids)
        )
        status.set_text(f"wrote {out_path.name}\nsegments: {lanelet_ids}")
        print(f"wrote {out_path}")
        print("add it to test_data/scenarios.yaml to run it")
        fig.canvas.draw_idle()

    generate_button = Button(plt.axes([0.82, 0.52, 0.15, 0.06]), "Generate")
    generate_button.on_clicked(on_generate)

    plt.show()


if __name__ == "__main__":
    main()
