/**:
  ros__parameters:
    node_hz: 5.0

    max_detection_range_m: 2.0

    include_unknown_objects: true

    sector_range:
      front: [-45.0, 45.0]
      front_left: [45.0, 100]
      rear_left: [100.0, 135.0]
      rear: [135, -135]
      rear_right: [-135.0, -100.0]
      front_right: [-100.0, -45.0]
