/**:
  ros__parameters:
    node_hz: 5.0

    max_detection_range_m: 2.0

    include_unknown_objects: true

    sector_range:
      front: [-22.5, 22.5]
      front_left: [22.5, 67.5]
      left: [67.5, 112.5]
      rear_left: [112.5, 157.5]
      rear: [157.5, -157.5]
      rear_right: [-157.5, -112.5]
      right: [-112.5, -67.5]
      front_right: [-67.5, -22.5]
