/**:
  ros__parameters:
    vehicle_kinematics:
      velocity_hard_mps: 11.1 # [m/s] (45 km/h)
      lon_accel_hard_min_mps2: -2.0 # [m/s^2] deceleration
      lon_accel_hard_max_mps2: 2.0 # [m/s^2] acceleration
      lon_jerk_hard_mps3: 5.0 # [m/s^3]
      lat_accel_hard_mps2: 1.5 # [m/s^2] about the limit of grip
      steer_rate_hard_radps: 0.256 # [rad/s]
