name: comment-on-pr

on:
  pull_request:
    types:
      - opened
    branches:
      - beta/v0.[0-9]+.[1-9]+

jobs:
  comment-on-pr:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - name: Create comments
        run: |
          cat << EOF > comments
          ### Merging guidelines for the beta branch
          Please use `Squash and merge` as the default.
          However, when incorporating multiple changes with cherry-pick, use a `Create a merge commit` to preserve the changes in the history.
          EOF
      - name: Post comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run: gh pr comment -F ./comments "${URL}"
