# Originally from https://github.com/autowarefoundation/sync-file-templates
# Customized: only PRs whose base branch name contains "e2e", and not opened by bots
# (GitHub user.type Bot, or login/display name containing "bot", case-insensitive).

name: comment-on-pr
on:
  pull_request:
    types: [opened]
    branches:
      # Base branch must contain "e2e" (e.g. tier4-e2e, release/e2e-foo)
      - "**e2e**"

jobs:
  comment-on-pr:
    if: github.event.pull_request.user.type != 'Bot' && !contains(toLower(github.event.pull_request.user.login), 'bot') && !contains(toLower(github.event.pull_request.user.name || ''), 'bot')
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Initial PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            @${{ github.event.pull_request.user.login }} Thank you for contributing to TIER IV E2E branch!
            Please check the following points before merging:
            - [ ] Write a brief description of this PR that can be understood by **coding-agents**.
            - [ ] Contact the branch manager on when the PR will be tested on vehicle.
            - [ ] Recommend to use **Squash and Merge** to merge the PR.
            - [ ] Report in #team-product-dev channel on the contents of the PR. @ branch manager.
