# This file is automatically synced from:
# https://github.com/autowarefoundation/sync-file-templates
# To make changes, update the source repository and follow the guidelines in its README.

name: comment-on-pr
on:
  pull_request_target:

jobs:
  comment-on-pr:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Initial PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            @${{ github.event.pull_request.user.login }} Thank you for contributing to TIER IV E2E branch!
            Please check the following points before merging:
            - [ ] Write a brief description of this PR that can be understood by **coding-agents**.
            - [ ] Contact the branch manager on when the PR will be tested on vehicle.
            - [ ] Recommend to use **Squash and Merge** to merge the PR.
            - [ ] Report in #team-product-dev channel on the contents of the PR. @ branch manager.
